/* 爆战丨无限弹幕 v2.6 · DOM UI App（只通过 GameState/GameBridge 通信） */
'use strict';
var isMobile=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||(window.innerWidth<=860&&'ontouchstart'in window);
var homeEl=document.getElementById('home'),slotBox=document.getElementById('slotBox'),listEl=document.getElementById('runeList'),resultPanel=document.getElementById('result');
var game=null,pendingRune=null,infoRune=null;
function refreshScale(){if(game&&game.scale&&game.scale.refresh)game.scale.refresh();}
function enterFullscreen(){var el=document.documentElement,req=el.requestFullscreen||el.webkitRequestFullscreen;if(!req)return false;try{var p=req.call(el);if(p&&p.then)p.then(function(){if(screen.orientation&&screen.orientation.lock)screen.orientation.lock('landscape').catch(function(){refreshScale();});setTimeout(refreshScale,200);setTimeout(refreshScale,700);}).catch(function(){refreshScale();});return true;}catch(e){refreshScale();return false;}}
function enterHome(){document.getElementById('guide').style.display='none';homeEl.style.display='flex';}
function loadoutUiBox(){return{centerX:94,centerY:188,matrixX:74,dividerX:128,heroX:172,scale:.56};}
function shortRuneName(def){return def.name.replace('符文','').replace('爆裂','爆').replace('寒冰','冰').replace('连锁','雷').replace('腐蚀','毒').replace('坚壁','盾');}
function ensureInfoPanel(){var p=document.getElementById('runeInfo');if(!p){p=document.createElement('div');p.id='runeInfo';p.className='rune-info';document.body.appendChild(p);}return p;}
function showRuneInfo(id,anchor){infoRune=id;var def=BZ.RUNE_DEFS[id],p=ensureInfoPanel();var tags=(def.tags||['技能']).map(function(t){return'<span>'+t+'</span>';}).join('');p.innerHTML='<div class="rih"><b>'+def.icon+' '+def.name+'</b><button type="button">×</button></div><div class="ritags">'+tags+'</div><div class="riattr">属性：'+(def.attr||'符文技能')+'</div><div class="ridesc">'+def.desc+'</div><div class="rienergy">充能上限：⚡'+def.energyMax+'</div>';p.querySelector('button').onclick=function(){p.style.display='none';infoRune=null;};p.style.display='block';var r=anchor.getBoundingClientRect(),left=Math.min(window.innerWidth-240,Math.max(8,r.left-8)),top=Math.min(window.innerHeight-132,Math.max(8,r.bottom+6));p.style.left=left+'px';p.style.top=top+'px';}
function hideRuneInfo(){var p=document.getElementById('runeInfo');if(p)p.style.display='none';infoRune=null;}
function ensureVersionPanel(){var p=document.getElementById('versionPopup');if(!p){p=document.createElement('div');p.id='versionPopup';p.className='version-popup';document.body.appendChild(p);}return p;}
function showVersionPopup(){var p=ensureVersionPanel();p.innerHTML='<div class="vph"><b>爆战丨无限弹幕 v2.6</b><button type="button">×</button></div><div class="vpcur">本次更新：符文矩阵收回边界内；虚线改为横向；横向/纵向间隔改为视觉等距。</div><details open><summary>历史更新</summary><div class="vplist"><div><b>v2.5</b> 英雄移到矩阵右侧</div><div><b>v2.4</b> 修复战斗完整显示、左侧版本入口</div><div><b>v2.3</b> 矩阵缩小、符文详情浮层、战斗三区重算</div><div><b>v2.2</b> 战斗基础三区与英雄缩小</div></div></details>';p.querySelector('button').onclick=function(){p.style.display='none';};p.style.display='block';}
function renderLoadout(){var box=loadoutUiBox(),slots=GameState.getLoadoutSlotView(box);slotBox.innerHTML='';var line=GameState.getDividerUiLine?GameState.getDividerUiLine(box):{x1:28,x2:128,y:188};var div=document.createElement('div');div.className='matrix-divider';div.style.left=Math.round(line.x1)+'px';div.style.top=Math.round(line.y)+'px';div.style.width=Math.round(line.x2-line.x1)+'px';slotBox.appendChild(div);for(var i=0;i<slots.length;i++)(function(s){var hex=document.createElement('button');hex.type='button';hex.className='hex slot-hex'+(s.def?' filled':' empty')+(pendingRune?' target':'');hex.style.left=(Math.round(s.point.x)-20)+'px';hex.style.top=(Math.round(s.point.y)-23)+'px';var inEl=document.createElement('div');inEl.className='hex-in';if(s.def){hex.style.background=cssColor(s.def.color);inEl.textContent=shortRuneName(s.def);inEl.style.color='#f8fafc';hex.onmouseenter=function(){showRuneInfo(s.runeId,hex);};hex.onmouseleave=function(){if(!isMobile)hideRuneInfo();};}else{hex.style.background='rgba(203,213,225,.45)';inEl.textContent='';}hex.onclick=function(){if(pendingRune){GameState.placeRuneAt(s.orderIndex,pendingRune);showRuneInfo(pendingRune,hex);pendingRune=null;renderLoadout();}else if(s.runeId){showRuneInfo(s.runeId,hex);GameState.clearRuneAt(s.orderIndex);renderLoadout();}};hex.appendChild(inEl);slotBox.appendChild(hex);})(slots[i]);var hp=GameState.getHeroUiPoint(box),hero=document.createElement('div');hero.className='hex hero-hex';hero.style.left=(Math.round(hp.x)-26)+'px';hero.style.top=(Math.round(hp.y)-30)+'px';var heroIn=document.createElement('div');heroIn.className='hex-in';heroIn.textContent='英雄';heroIn.style.color='#dbeafe';hero.appendChild(heroIn);slotBox.appendChild(hero);listEl.innerHTML='';BZ.RUNE_ORDER.forEach(function(id){var def=BZ.RUNE_DEFS[id],slot=GameState.getRuneSlot(id),on=slot>=0,row=document.createElement('button');row.className='rune-row'+(on?' on':'')+(pendingRune===id?' pick':'');row.innerHTML='<span class="ri">'+def.icon+'</span><span class="rt"><span class="rn">'+def.name+(on?' · 已装配':'')+'</span><span class="rd">'+def.desc+'</span></span><span class="re">⚡'+def.energyMax+'</span>';row.onmouseenter=function(){showRuneInfo(id,row);};row.onmouseleave=function(){if(!isMobile)hideRuneInfo();};row.onclick=function(){pendingRune=(pendingRune===id?null:id);showRuneInfo(id,row);renderLoadout();};listEl.appendChild(row);});var hint=pendingRune?'已选择「'+BZ.RUNE_DEFS[pendingRune].name+'」：点击左侧符文槽装配':'横向虚线分隔上下符文区；先点符文，再点槽位';document.getElementById('selCount').textContent='已装配 '+GameState.getEquippedCount()+' / 5 · '+hint;}
function showResult(r){var title=document.getElementById('resultTitle');title.textContent=r.win?'胜利':'失败';title.style.color=r.win?'#4ade80':'#f87171';document.getElementById('resultStats').textContent='用时 '+r.time.toFixed(1)+' 秒 · 击杀 '+r.kills;resultPanel.style.display='flex';}
function startBattleFromState(){var cfg=GameState.createBattleConfig();homeEl.style.display='none';resultPanel.style.display='none';hideRuneInfo();GameBridge.emit('battle:start',cfg);}
GameBridge.on('battle:start',function(cfg){if(!game){game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#0b1020',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[BattleScene]});}var s=game.scene.getScene('battle');if(s)s.scene.restart(cfg);else game.scene.start('battle',cfg);setTimeout(refreshScale,100);setTimeout(refreshScale,500);});
GameBridge.on('battle:ended',showResult);GameBridge.on('battle:failed',showResult);GameBridge.on('battle:restart',startBattleFromState);
function setupFullscreen(){var gStart=document.getElementById('btnGuideStart'),gSkip=document.getElementById('btnGuideSkip'),gHint=document.getElementById('guideHint'),mini=document.getElementById('btnFsMini');if(gStart)gStart.onclick=function(){if(enterFullscreen())enterHome();else{gHint.innerHTML='当前浏览器不支持网页全屏。<b>推荐：添加到主屏幕后打开。</b>或手动横屏后点「继续」。';gSkip.style.display='block';}};if(gSkip)gSkip.onclick=function(){enterHome();if(isMobile)alert('请手动旋转手机至横屏进行游戏');};if(mini)mini.onclick=function(){if(document.fullscreenElement||document.webkitFullscreenElement){var exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)exit.call(document);}else enterFullscreen();};document.addEventListener('fullscreenchange',function(){refreshScale();if(mini)mini.textContent=document.fullscreenElement?'✕':'⛶';});window.addEventListener('resize',function(){setTimeout(refreshScale,120);});window.addEventListener('orientationchange',function(){setTimeout(refreshScale,120);});}
function setupTabs(){var btns=document.querySelectorAll('.tab-btn'),pages={runes:'pageRunes',mastery:'pageMastery',equip:'pageEquip',settings:'pageSettings'};for(var i=0;i<btns.length;i++)btns[i].onclick=function(){hideRuneInfo();var tab=this.getAttribute('data-tab');for(var j=0;j<btns.length;j++)btns[j].className='tab-btn'+(btns[j]===this?' on':'');for(var key in pages)document.getElementById(pages[key]).className='page'+(key===tab?' on':'');};var reset=document.getElementById('btnResetSave');if(reset)reset.onclick=function(){if(confirm('确定重置本地存档？已装配符文等数据将清空。')){GameState.resetSave();location.reload();}};}
document.getElementById('btnStart').onclick=startBattleFromState;document.getElementById('btnAgain').onclick=startBattleFromState;document.getElementById('btnLoadout').onclick=function(){resultPanel.style.display='none';homeEl.style.display='flex';renderLoadout();};setupFullscreen();setupTabs();renderLoadout();var vb=document.getElementById('versionBadge');if(vb){vb.onclick=showVersionPopup;vb.onmouseenter=showVersionPopup;}setTimeout(refreshScale,300);
